language: generic
sudo: required
services:
  - docker

before_install:
  - travis_wait docker build -t andreibercea/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true andreibercea/docker-react npm run test
