FROM node:14-alpine

ENV HTTP_PROXY="http://10.31.255.65:8080"
ENV HTTPS_PROXY="http://10.31.255.65:8080"

WORKDIR '/app'

COPY package*.json ./

RUN pnpm install

COPY . .

CMD ["npm", "run", "start"]
